<template><LegalPage title="Coach Commission Terms" effective-date="September 23, 2026" intro="Athletes use Runnit for free. Runnit earns from successful paid coaching transactions rather than charging athletes for core access." :sections="sections" /></template>
<script setup>
import { useHead } from '@unhead/vue'
import LegalPage from '@/components/LegalPage.vue'
useHead({ title:'Coach Commission Terms — Runnit' })
const sections = [
  { id:'rate', title:'1. Default platform commission', blocks:[{ text:'Unless a service listing or written promotion states otherwise, Runnit’s platform commission is 15% of the gross service amount paid by the athlete. The applicable commission and any processing adjustments are shown to the coach before a service is published or materially changed.' },{ text:'The commission is charged only when an athlete successfully pays for a service. Runnit does not charge a recurring athlete subscription for core access.' }]},
  { id:'processing', title:'2. Processing and payout adjustments', blocks:[{ text:'Payment processors may deduct payment-processing, currency-conversion, dispute, or payout fees. These amounts, taxes, required withholding, refunds, chargebacks, and other adjustments may reduce the amount shown as coach net earnings.' },{ text:'Payout timing is subject to processor rules, verification, risk review, the cancellation window, and successful delivery. Do not promise an athlete a payout date.' }]},
  { id:'refunds', title:'3. Refunds, cancellations, disputes', blocks:[{ text:'When a booking is refunded or reversed, Runnit may reverse the related commission and payout. A chargeback, fraud review, dispute, or coach no-show may place funds on hold while the issue is reviewed.' },{ text:'Coaches must honor the cancellation policy shown on their listing and respond to support requests with accurate records. Runnit may use booking, calendar, message, and delivery evidence to administer a dispute.' }]},
  { id:'connect', title:'4. Payout account and tax records', blocks:[{ text:'Coaches must complete Stripe Connect or another approved payout provider’s onboarding, identity verification, and tax information requirements. Keep payout and tax details current. Runnit does not provide tax advice; consult a qualified tax professional about reporting and obligations.' },{ text:'Runnit may provide transaction records or receipts. Payment processors may issue tax forms where required. Coaches are responsible for reviewing records and reporting income as required.' }]},
  { id:'changes', title:'5. Changes and acceptance', blocks:[{ text:'Runnit may change the commission, payout schedule, eligible services, or fee treatment with notice. A new rate applies to future bookings after its effective date, not to a completed booking unless required to correct an error or process a reversal. Publishing or continuing to offer services after the effective date constitutes acceptance.' }]}
]
</script>
