<template><LegalPage title="Coach Agreement" effective-date="September 23, 2026" intro="This agreement applies when a coach creates a marketplace profile, publishes a service, accepts a booking, or receives a payout through Runnit." :sections="sections" /></template>
<script setup>
import { useHead } from '@unhead/vue'
import LegalPage from '@/components/LegalPage.vue'
useHead({ title:'Coach Agreement — Runnit' })
const sections = [
  { id:'relationship', title:'1. Independent coach relationship', blocks:[{ text:'You are an independent service provider, not a Runnit employee, agent, partner, or medical provider. You control how you deliver your services, subject to your listing, applicable law, safety requirements, and this Agreement. You are responsible for your taxes, insurance, licenses, certifications, equipment, and professional obligations.' }]},
  { id:'profile', title:'2. Coach profile and services', blocks:[{ text:'Provide accurate experience, certifications, specialties, prices, availability, service descriptions, cancellation terms, and identity information. Do not claim credentials you do not hold, promise medical outcomes, or market a service as emergency or clinical care.' },{ text:'Keep listings, calendar availability, communications, and delivery status current. A coach must personally deliver the service unless the athlete clearly agrees to another qualified provider.' }]},
  { id:'athlete-data', title:'3. Athlete data and privacy', blocks:[{ text:'Use athlete data only to deliver the booked service and related communication. Keep it confidential, secure, and limited to what is necessary. Do not export, sell, publish, or reuse GPS, health, recovery, activity, or contact data for another purpose without permission and a lawful basis.' },{ text:'Respect athlete privacy settings and deletion requests. Report suspected exposure or unauthorized access to support@runnit.live promptly.' }]},
  { id:'safety', title:'4. Safety and conduct', blocks:[{ text:'Treat athletes respectfully and do not harass, discriminate, exploit, or pressure them. Follow the Medical Disclaimer, disclose relevant limitations, refer medical concerns to qualified professionals, and stop or modify a session when safety requires it.' },{ text:'Runnit may review reports, messages, reviews, credentials, listings, bookings, and payouts. We may remove listings, pause payouts, suspend, or terminate an account for safety, fraud, policy, or legal reasons.' }]},
  { id:'money', title:'5. Payments, refunds, and commission', blocks:[{ text:'Athletes pay through the checkout flow. Stripe or another processor handles payment and payout mechanics. You authorize Runnit to deduct the platform commission, processing adjustments, refunds, chargebacks, taxes or withholdings required by law, and other amounts disclosed before payout.' },{ text:'Refunds, cancellations, disputes, and chargebacks may reduce or reverse your payout. Review the Coach Commission Terms and Refund Policy before publishing a service.' }]},
  { id:'content', title:'6. Content and reviews', blocks:[{ text:'You retain ownership of content you provide, but grant Runnit a limited license to host and display your profile, service listing, availability, messages, and reviews to operate the marketplace. Do not upload content you do not have rights to use.' },{ text:'Reviews must reflect a genuine experience and may not be fabricated, coerced, retaliatory, or exchanged for payment.' }]},
  { id:'acceptance', title:'7. Acceptance and changes', blocks:[{ text:'By checking the coach agreement box or publishing a service, you accept this Agreement, the Terms of Service, Coach Commission Terms, Refund Policy, Medical Disclaimer, and applicable marketplace disclosures. Runnit may update these terms; material changes will be presented before continued marketplace use where appropriate.' }]}
]
</script>
