<template><LegalPage title="Privacy Policy" effective-date="September 23, 2026" intro="This policy describes the information Runnit collects, why we use it, when it is shared, and the choices available to you." :sections="sections" /></template>
<script setup>
import { useHead } from '@unhead/vue'
import LegalPage from './LegalPage.vue'
useHead({ title: 'Privacy Policy — Runnit', meta: [{ name: 'description', content: 'How Runnit handles account, training, GPS, health, integration, social, coach, payment, and rewards data.' }] })
const sections = [
  { id:'scope', title:'1. Scope and controller', blocks:[{ text:'This Privacy Policy applies to Runnit at runnit.live, the Runnit mobile applications, and related services. The final published version should identify the correct legal entity, address, privacy contact, and any regional representative.' }]},
  { id:'collect', title:'2. Information we collect', blocks:[{ heading:'You provide', list:['Name, email, login provider, profile, location, sport, preferences, and account settings','Activities, plans, folders, strength logs, race history, comments, photos, GIFs, messages, and other content','Coach profile, credentials, specialties, services, availability, reviews, and marketplace communications','Support requests, survey responses, and choices about privacy, notifications, and marketing'] },{ heading:'You authorize', text:'Connected services may provide workout, recovery, heart-rate, sleep, GPS, route, race, music, and device data, depending on the services you choose to connect.' },{ heading:'Collected automatically', text:'We collect device, browser, approximate location, IP address, log, request ID, diagnostic, cookie, analytics, and feature-use information needed to secure and improve the Service.' }]},
  { id:'use', title:'3. How we use information', blocks:[{ list:['Provide accounts, profiles, activities, plans, training analytics, social features, coaching, rewards, and support','Import, normalize, deduplicate, and display information from connected services at your direction','Personalize onboarding, recommendations, coaching prompts, challenges, and product messages','Process payments, payouts, refunds, receipts, fraud checks, and marketplace operations','Monitor reliability, prevent abuse, troubleshoot errors, measure adoption, and improve the product','Comply with law, enforce our terms, and protect users, Runnit, and the public'] },{ text:'Runnit should not sell personal information or use health, GPS, or workout data for third-party advertising. If our practices change, we will update this policy and provide any notice required by law.' }]},
  { id:'share', title:'4. How information is shared', blocks:[{ text:'Your public profile, activities, posts, comments, race history, and social interactions are visible according to the settings you choose. Coaches only receive training data or messages that you authorize for a coaching relationship or booking.' },{ text:'We use service providers for hosting, databases, analytics, email, customer support, maps, authentication, payment processing, payouts, fraud prevention, and integration APIs. They may process information only to provide services to Runnit under appropriate agreements.' },{ text:'We may disclose information when required by law, to protect safety or rights, to investigate abuse, or as part of a merger, financing, acquisition, or sale of assets. We do not share private training data with a coach, partner, or other user without a product action or consent that authorizes it.' }]},
  { id:'integrations', title:'5. Connected services', blocks:[{ text:'When you connect a supported provider, you authorize Runnit to receive the scopes shown in that provider’s consent flow. Disconnecting stops future requests where supported; it does not automatically erase imported records already stored in Runnit.' },{ text:'You can manage integrations and permissions in Devices or Settings. Contact privacy@runnit.live to request deletion of imported data or to ask what remains after disconnecting. Third-party providers have their own privacy policies and controls.' }]},
  { id:'retention', title:'6. Retention, security, and deletion', blocks:[{ text:'We retain information for as long as needed to provide the Service, maintain legitimate business records, resolve disputes, enforce terms, prevent abuse, and meet legal obligations. Retention periods vary by data type and product state.' },{ text:'We use administrative, technical, and organizational safeguards, but no service can guarantee absolute security. Do not place emergency, highly sensitive medical, or other information in public posts or messages.' },{ text:'You can change visibility settings, disconnect providers, export available data, or request correction/deletion by contacting privacy@runnit.live. We may retain limited information where required or permitted by law.' }]},
  { id:'choices', title:'7. Your choices and rights', blocks:[{ text:'You can control profile and activity visibility, integration connections, notification preferences, marketing messages, cookies where available, and coach data-sharing settings. Depending on where you live, you may have rights to access, correct, delete, restrict, object to, or receive a copy of personal information, and to appeal a decision.' },{ text:'To make a request, email privacy@runnit.live with enough information for us to verify and respond. We will not discriminate against you for exercising applicable privacy rights. Counsel should confirm regional notices, timelines, identity verification, and appeal procedures before launch.' }]},
  { id:'children', title:'8. Children and changes', blocks:[{ text:'Runnit is not directed to children under 13, or the higher minimum age required where they live. If you believe a child provided information improperly, contact us.' },{ text:'We may update this policy as the product changes. We will post the new effective date and provide additional notice for material changes where required.' }]}
]
</script>
