<template><LegalPage title="Terms of Service" effective-date="September 23, 2026" intro="These terms explain how Runnit works as a free training and social platform, and how the optional coach marketplace, integrations, rewards, and user content fit together." :sections="sections" /></template>
<script setup>
import { useHead } from '@unhead/vue'
import LegalPage from './LegalPage.vue'
useHead({ title: 'Terms of Service — Runnit', meta: [{ name: 'description', content: 'Runnit Terms of Service for the training platform and coach marketplace.' }] })
const sections = [
  { id:'agreement', title:'1. Agreement and eligibility', blocks:[{ text:'By accessing Runnit, you agree to these Terms. If you do not agree, do not use the Service. You must be at least 13 years old, or the minimum age required where you live. If you are under 18, a parent or guardian must approve your use.' },{ text:'Runnit is currently designed to provide free athlete access. We may offer optional paid products, coaching services, partner offers, or rewards fulfillment, each with additional terms shown before purchase.' }]},
  { id:'accounts', title:'2. Accounts and security', blocks:[{ text:'Keep your registration information accurate and your credentials secure. You are responsible for activity on your account and must promptly report unauthorized access. You may request account deletion through Settings or by contacting support.' },{ text:'We may suspend or close accounts for fraud, abuse, safety issues, unlawful conduct, or material violations of these Terms. We will provide notice where reasonable and legally required.' }]},
  { id:'data', title:'3. Training data and integrations', blocks:[{ text:'Runnit can display training, recovery, GPS, health, music, and activity information that you enter manually or authorize through supported connected services. You control which integrations you connect and which activities you share.' },{ text:'Third-party integrations are provided by their respective providers and may change, pause, or disconnect. Runnit does not guarantee the accuracy, completeness, or availability of imported data.' }]},
  { id:'community', title:'4. Community and user content', blocks:[{ text:'You keep ownership of content you post. You grant Runnit a limited, worldwide, non-exclusive license to host, display, reproduce, and distribute it only as needed to operate, secure, and improve the Service. You are responsible for having the rights to what you upload.' },{ heading:'You may not:', list:['Harass, threaten, impersonate, or target another person','Post unlawful, hateful, deceptive, private, or infringing content','Upload malware, scrape the Service, or bypass access controls','Manipulate activity, rankings, rewards, reviews, or marketplace transactions','Share another person’s health, location, or training data without permission'] }]},
  { id:'coaching', title:'5. Coach marketplace', blocks:[{ text:'Runnit provides tools for independent coaches and athletes to discover services, communicate, book, and pay. Runnit is not the coach, employer, medical provider, or contracting party for a coaching service. The coach is responsible for the service, price, availability, credentials, advice, and delivery.' },{ text:'Coach listings, bookings, payments, refunds, cancellations, commission, privacy consent, and medical disclosures are also governed by the Coach Agreement and Coach Commission Terms. Review them before publishing or purchasing a service.' }]},
  { id:'payments-rewards', title:'6. Payments and rewards', blocks:[{ text:'Payment terms, processing fees, taxes, refunds, and cancellations are shown at checkout or in the applicable policy. Stripe and other payment partners may process transactions and apply their own terms.' },{ text:'Runnit rewards may be promotional, limited, unavailable, substituted, or subject to eligibility and abuse controls. A reward is not cash and cannot be transferred unless Runnit expressly says otherwise.' }]},
  { id:'health', title:'7. Health and safety', blocks:[{ text:'Runnit is a training and social product, not a medical service. Metrics, plans, coach content, recommendations, and AI-generated information are educational and may be wrong or unsuitable. Read the Medical Disclaimer and consult a qualified clinician before changing exercise, nutrition, or recovery routines.' },{ text:'Stop activity and seek appropriate care for pain, injury, illness, or an emergency. Never rely on Runnit as a substitute for emergency services or professional medical advice.' }]},
  { id:'availability', title:'8. Availability and liability', blocks:[{ text:'The Service is provided as available. We may modify, suspend, or discontinue features, integrations, rewards, or marketplace tools. To the fullest extent permitted by law, Runnit is not liable for indirect, incidental, special, consequential, or punitive losses.' },{ text:'To the fullest extent permitted by law, Runnit’s total liability for a claim relating to the Service will not exceed the greater of the amount you paid Runnit in the prior 12 months or $100 USD.' }]},
  { id:'law', title:'9. General terms', blocks:[{ text:'These Terms are governed by the law stated in the final published version for the Runnit operating entity, without regard to conflict-of-law rules. Counsel should confirm the entity, jurisdiction, dispute process, arbitration language, consumer rights, and any required regional addenda before launch.' },{ text:'If one provision is unenforceable, the remaining provisions remain effective. The English version controls unless applicable law requires otherwise.' }]}
]
</script>
